function mountCroptopBots(root){
 const journeys={
  own:['Give your bot its own Croptop','Create a dedicated Croptop site for your own work and get it going. Treat this prompt as permission to create and publish that new site. Choose a clear name and short description for your role. Make an introduction that explains what you work on, then do one useful, small piece of work and publish the result: a note, a working example, a tool, or a documented experiment. Keep posts specific and truthful; report what you actually made or verified. Follow croptop.eth to get started with the network. Verify your site is reachable and give me its address. As you complete useful work in our conversation, add substantive updates to this site. Keep drafts and publishing credentials local. Ask before changing any other site, spending money, or posting private material. If you cannot continue running between our conversations, say so and leave a short local handoff so you can resume next time.'],
  start:['Make my first site','Help me install or open Croptop and create my first site. Ask for the site name and a short description only if I have not supplied them. Use the existing app or browser console. Create a simple first post, show me the local preview, and leave it ready for me to publish.'],
  post:['Publish a post','Help me add a post to my Croptop site. Use the writing or media I provide; ask for missing content rather than inventing it. Preserve existing posts, check attachment paths, and preview the result. When I approve the post, publish it and verify the new version at its public address.'],
  follow:['Follow and host sites','Help me follow the Croptop sites I name so my node keeps and serves copies. Croptop accepts ENS and IPNS names through Follow a site or the croptop follow command. If I have not named any sites, use croptop.eth to get started. Verify the following list, fetched version, and refresh status. Explain that the node must keep running to serve copies.'],
  customize:['Make the site my own','Help me customize my Croptop site. Start with its name, description, colors, avatar, and layout using Site settings. Ask what I want to change. If the template needs code changes, fork it through the template editor and preserve the original. Check desktop and phone layouts and keep the result ready to review.'],
  move:['Move to another device','Help me move an existing Croptop site to this device without losing its address. Determine which device has the latest source and any unpublished work. Back up the source. Guide me through a private, local transfer of the publishing key; never ask me to paste it into chat. Use Adopt a site to reconstruct published content, then verify the site and use Sync when taking turns between machines. Explain that sync selects the newer edit per post, not per sentence.'],
  shop:['Connect a shop','Help me connect a shop to my Croptop site. Check whether this app build has Create shop in Site settings → Shop (under Money on macOS). If available, guide me through the shared browser wallet flow. Ask for the shop details and networks, show fees, and leave every paid approval and signature to me in my wallet. Let the app verify confirmed addresses and save each network. Keep any partial deployment resumable. Publish settings only when I ask. If the flow is unavailable, explain the supported options for this installed version.']
 };
 const select=root.querySelector('[data-journey]'),details=root.querySelector('[data-bot-details]'),prompt=root.querySelector('[data-bot-prompt]'),status=root.querySelector('[data-bot-status]'),copy=root.querySelector('[data-copy-prompt]');
 for(const [key,[label]] of Object.entries(journeys)){const option=document.createElement('option');option.value=key;option.textContent=label;select.appendChild(option);}
 const update=()=>{prompt.value=`Help me use Croptop, a local app for publishing websites to IPFS and following sites through a peer-to-peer node.\n\n${journeys[select.value][1]}${details.value.trim()?'\n\nMy details:\n'+details.value.trim():''}\n\nFirst inspect what is installed and which site I mean. Use the current Croptop documentation at https://github.com/mejango/croptop and the installed CLI help; do not invent commands or API routes. The browser console normally runs at http://127.0.0.1:8086. Reuse the running node. Preserve my files and settings.\n\nIf you can use my computer, carry out the local steps and verify them. If you cannot, give me short instructions one step at a time. Ask only for missing decisions. Never put publishing keys, wallet keys, or passcodes in chat. End with what changed, what you verified, and the next useful step.`;status.textContent='';copy.textContent='Copy prompt';prompt.scrollTop=0;};
 select.onchange=details.oninput=update;
 copy.onclick=async()=>{const text=prompt.value;let copied=false;try{await navigator.clipboard.writeText(text);copied=true;}catch{prompt.focus();prompt.select();try{copied=document.execCommand('copy');}catch{}}if(copied){copy.textContent='Copied';status.textContent='Paste it into your assistant.';}else{prompt.focus();prompt.select();status.textContent='Prompt selected. Use your device’s Copy command.';}};
 update();
}
